theme: jekyll-theme-cayman

# Site settings
title: cloudy theology
email: josh@joshware.com
description: > # this means to ignore newlines until "baseurl:"
  a hacker writes on faith, technology and conscience...and draws pictures.
baseurl: ""#"/zh2017" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://joshware.com" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown
