theme: jekyll-theme-cayman
# Site settings
title: cloudy theology
email: josh@joshware.com
description: > # this means to ignore newlines until "baseurl:"
  a hacker writes on faith, technology and conscience...and draws pictures.
baseurl: ""#"/zh2017" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://joshware.com" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: joshware

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "Simple Blog Theme"
  short_bio:
    en: Jekyll Blog Theme, Responsive, SEO and Facebook enabled
    it: Jekyll Blog Theme, Responsive, con SEO e integrazione Facebook
  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

t:
  en:
    latest-posts:  "Latest Posts"
    read-more:  "read more"
    on-word: "on"
    contact: "Contact"
    contact-page: "contact.md"
    comments: "comments"
    go-to-home-page: "Go to the Home Page"
    months:
      january: "Jan"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "May"
      june: "Jun"
      july: "Jul"
      august: "Aug"
      september: "Sep"
      october: "Oct"
      november: "Nov"
      december : "Dec"
  it:
    latest-posts:  "Ultimi Posts"
    read-more:  "leggi"
    on-word: "su"
    contact: "Contatta"
    contact-page: "contatta.md"
    comments: "commenti"
    go-to-home-page: "Vai alla Pagina Iniziale"
    months:
      january: "Gen"
      february: "Feb"
      march: "Mar"
      april: "Apr"
      may: "Mag"
      june: "Giu"
      july: "Lug"
      august: "Ago"
      september: "Set"
      october: "Ott"
      november: "Nov"
      december : "Dic"

defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "en"
      category: undefined


##
# Parameters for WikiToJekyll
# Used by Rake:wikisub, Rake:wiki and wikiLinks generator plugin
##
wikiToJekyll:

  # your user Github Name
  user_name: joshwarecom

  # your repository Name
  repository_name: joshwarecom.github.com

  # set your remote name. 'origin' is the default name set
  # when you do a 'git init'
  # if you changed this name be sure to change this parameter
  deploy_remote: "origin"

  # for an organization / user, publication branch is master
  # for a project, publication branch is gh-pages
  deploy_branch: "gh-pages"

  # wiki repository url
  # if you live this blank, it will be derived from you code
  # user_name and repository_name
  #   eg : wiki_repository_url = user_name/repository_name/wiki'
  #
  # If you're importing a wiki from another code repository
  # you MUST set this url
  #
  # IMPORTANT: no git@github.com: in front
  #            You MUST use the htpps:// url or it will
  #            cause a submodule error on github
  #
  # Example : https://github.com/userName/repositoryName.wiki.git

  wiki_repository_url: # https://github.com/joshwarecom/joshwarecom.github.com.wiki.git

  # wiki submodule folder
  # the underscore makes sure that this folder is ignored by Jekyll
  wiki_source: "_wiki"

  # wiki Jekyll generated pages destination folder
  wiki_dest: "wiki"

  # commit and push to Jekyll repository after wiki synchronisation
  commit_and_push: false
