# Dependencies
markdown:         kramdown

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
shortcut:         joshware.com
title:            cloudy theology
tagline:          '{ a web-aware witness wiki }'
description:      '{ a web-aware witness wiki }'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

zhdebug:            true

subsites:
    - component: tc
      title: technocentric criticism
      tagline:     excavating the Bible's high-tech heritage
      description: excavating the Bible's high-tech heritage
      homelinktxt: primer
    - component: 
      title: cloudy theology
      tagline:     '{ a web-aware witness wiki }'
      description: '{ a web-aware witness wiki }'
      homelinktxt: recent updates
      
author:
  name:           'Joshua Wilson'
  url:            http://joshware.com

# Custom vars
version:             1.0.0
