#!/bin/bash
token=$1;
firewallid=$2;
ip6list=$3
user_idex=$4;
>&2 echo -n $4
curl -s -H "Content-Type: application/json" \
    -H "Authorization: Bearer $token" \
    -X PUT -d '{
        "inbound": [
          {
            "protocol": "TCP",
            "ports": "3010",
            "addresses": {
              "ipv6": [
                '"$ip6list"'
              ]
            },
          "action": "ACCEPT",
          "label": "allow-app-hacking-traffic"
          }
        ]
    }' \
    https://api.linode.com/v4/networking/firewalls/$firewallid/rules