/* resourcemap.js generated by blorbtool.py */
StaticImageInfo = {
1: {
  "image": 1,
  "url": "interpreter\\pict-1.jpeg",
  "width": 680,
  "height": 680
}
,
3: {
  "image": 3,
  "url": "interpreter\\pict-3.jpeg",
  "width": 586,
  "height": 330
}
,
4: {
  "image": 4,
  "url": "interpreter\\pict-4.jpeg",
  "width": 586,
  "height": 330
}
,
5: {
  "image": 5,
  "url": "interpreter\\pict-5.jpeg",
  "width": 586,
  "height": 330
}
,
6: {
  "image": 6,
  "url": "interpreter\\pict-6.png",
  "width": 586,
  "height": 330
}
};
