cmd: "E:\\tools\\inform\\inform6.exe"
name: "E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\{FILE_ACTIVE_NAME}"
args:
  - +include_path=E:\\Progra~2\\Imaginate\\Projects\\Inform\\pristine\\inform6\\lib,E:\\Progra~2\\Imaginate\\Projects\\Inform\\pristine\\vorple-i6
  - +language_name=portl-english
  - $MAX_STATIC_DATA=180000
  - -s
  - -G
  - "E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\{FILE_ACTIVE_NAME}"
  - "E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\bin\\{FILE_ACTIVE_NAME_BASE}.ulx"
  - "&& copy E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\{FILE_ACTIVE_NAME_BASE}-play.html E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\lib\\output.html && copy E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\bin\\{FILE_ACTIVE_NAME_BASE}.ulx E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\lib\\output.ulx && start E:\\git\\joshwarecom.github.com\\sandbox\\if\\vorple-i6\\pserve.bat && start http://localhost:8000/lib/output.html"
sh: true,
cwd: "E:\\tools\\inform\\"
errorMatch:
  - "(?<file>([a-zA-Z]:.+))\\((?<line>(\\d+))\\): Error: (?<message>(.+))"
  - "(?<file>([a-zA-Z]:.+))\\((?<line>(\\d+))\\): Fatal error: (?<message>(.+))"
warningMatch:
  - "(?<file>([a-zA-Z]:.+))\\((?<line>(\\d+))\\): Warning: (?<message>(.+))"
